---
- name: Setup Database Server
  hosts: database
  become: yes
  vars:
    mysql_root_password: "RootPass123!"
    db_name: "hospital_db"
    db_user: "hospital_user"
    db_password: "HospitalPass123!"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MySQL and dependencies
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-pymysql
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Wait for MySQL to be ready
      wait_for:
        port: 3306
        delay: 5
        timeout: 30

    - name: Create hospital database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Configure MySQL for remote access
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: restart mysql

    - name: Copy database schema file
      copy:
        src: "{{ playbook_dir }}/../hospital_app/db/schema.sql"
        dest: /tmp/hospital_schema.sql

    - name: Import database schema
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /tmp/hospital_schema.sql
        login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted

